# Generated by Django 5.1.2 on 2024-10-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(verbose_name='User Created At')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('expense', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(verbose_name='User Created At')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseAPI.user')),
            ],
        ),
    ]
