# Generated by Django 5.1.2 on 2024-10-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='createdat',
            field=models.DateTimeField(null=True, verbose_name='User Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(null=True, verbose_name='User Created At'),
        ),
    ]
